### ISSUE TITLE
Does not work in Microsoft browsers

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#35] opened 2016-04-22 14:37 UTC
Hey,
I just tried to pull this up in internet explorer and none of the dots came up. Also someone mentioned trying to use Microsoft Edge and it did not work.
~Matt

**Comment by ghing** [comment] 2016-04-22 15:30
I just double checked that this worked ok in Firefox.  Updating the title to reflect specific Microsoft issues.

**Comment by ghing** [comment] 2016-04-22 15:31
@Mattwalsh129 can you add which version of Internet Explorer you're using?

**Comment by Mattwalsh129** [comment] 2016-04-22 15:33
Internet Explorer 11

On Fri, Apr 22, 2016 at 10:31 AM, Geoffrey Hing <notifications@github.com>
wrote:

> @Mattwalsh129 <https://github.com/Mattwalsh129> can you add which version
> of Internet Explorer you're using?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/35#issuecomment-213475758>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment] 2016-04-22 15:35
Can you open the F12 developer tools, then reload the page, then copy and paste what's in the "Console" tab.  That will help me diagnose the problem more quickly: https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx

**Comment by Mattwalsh129** [comment] 2016-04-22 15:41
DOM7011: The code on this page disabled back and forward caching. For more
information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: learning-collaborative-maps.herokuapp.com

HTML1300: Navigation occurred.
File: learning-collaborative-maps.herokuapp.com


On Fri, Apr 22, 2016 at 10:35 AM, Geoffrey Hing <notifications@github.com>
wrote:

> Can you open the F12 developer tools, then reload the page, then copy and
> paste what's in the "Console" tab. That will help me diagnose the problem
> more quickly:
> https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/35#issuecomment-213477573>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment] 2016-04-23 21:39
Using BrowserStack to try to debug this on IE 11. Oh wow, BrowserStack can handle local URLs!

No relevant errors in JavaScript console.

JSON is getting requested and request seems ok.

Added debugging messages to code.  Looks like handler for schools request is running.  Also render method of map component.

Looked at DOM.  Marker elements not being created.

After adding a bunch of debugging messages it looks like the issue is in the `_styleSchoolMarker` method.

Ran out of free minutes on BrowserStack.  Downloading the [IE virtual machine](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) now.

**Comment by ghing** [comment] 2016-05-04 01:17
So it looks like the actual problem is in `distinctProgramAgencies()`.  I'm guessing that IE doesn't have the support for `Set()` that we need.  The [MDN article on Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) says IE doesn't have support as an iterable.  Playing in the dev console shows it does have `forEach`.  Maybe try an uglier way to convert it to a list.

**Comment by ghing** [comment] 2016-05-04 01:52
Closed by 05e899b585c53146d1243aa54f91c70ea8a52d1a

**Closed by ghing** 2016-05-04 01:52 UTC
Labels: bug
